dependencies {
    elytraModpackVersion {
        // 在这配置的gtnh版本 用于自动拉取依赖版本
        gtnhVersion = "2.9.0-beta-2"
        // 是否不缓存拉取的依赖清单文件
        manifestNoCache = false
        // 是否自动为输出的jar添加 `gtnhVersion` 后缀
        attachManifestVersionToJar = false
    }
//Write deps here
    //Placeholder
    implementation('org.joml:joml:1.10.8')
    implementation('com.github.GTNewHorizons:Hodgepodge:2.7.190:dev')
    compileOnly('it.unimi.dsi:fastutil:8.5.18')
    annotationProcessor('com.google.auto.value:auto-value:1.10.1')
    implementation('com.google.auto.value:auto-value-annotations:1.10.1')
    runtimeOnlyNonPublishable('com.github.GTNewHorizons:Angelica:2.2.8:dev')
    runtimeOnlyNonPublishable(gtnhDev("NotEnoughItems"))





}

@SuppressWarnings('GrMethodMayBeStatic')
String gtnhDev(String name, String classifier = "dev") {
    return elytraModpackVersion.gtnh(name, classifier)
}

